//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja.ReferenciaServicioUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicioUsuario.ServicioAutSoap")]
    public interface ServicioAutSoap {
        
        // CODEGEN: Generating message contract since element name nombreUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutetnticacionUsuario", ReplyAction="*")]
        Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioResponse AutetnticacionUsuario(Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutetnticacionUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioResponse> AutetnticacionUsuarioAsync(Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutetnticacionUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutetnticacionUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequestBody Body;
        
        public AutetnticacionUsuarioRequest() {
        }
        
        public AutetnticacionUsuarioRequest(Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutetnticacionUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string claveUsuario;
        
        public AutetnticacionUsuarioRequestBody() {
        }
        
        public AutetnticacionUsuarioRequestBody(string nombreUsuario, string claveUsuario) {
            this.nombreUsuario = nombreUsuario;
            this.claveUsuario = claveUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutetnticacionUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutetnticacionUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioResponseBody Body;
        
        public AutetnticacionUsuarioResponse() {
        }
        
        public AutetnticacionUsuarioResponse(Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutetnticacionUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AutetnticacionUsuarioResult;
        
        public AutetnticacionUsuarioResponseBody() {
        }
        
        public AutetnticacionUsuarioResponseBody(bool AutetnticacionUsuarioResult) {
            this.AutetnticacionUsuarioResult = AutetnticacionUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioAutSoapChannel : Caja.ReferenciaServicioUsuario.ServicioAutSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAutSoapClient : System.ServiceModel.ClientBase<Caja.ReferenciaServicioUsuario.ServicioAutSoap>, Caja.ReferenciaServicioUsuario.ServicioAutSoap {
        
        public ServicioAutSoapClient() {
        }
        
        public ServicioAutSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAutSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAutSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAutSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioResponse Caja.ReferenciaServicioUsuario.ServicioAutSoap.AutetnticacionUsuario(Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequest request) {
            return base.Channel.AutetnticacionUsuario(request);
        }
        
        public bool AutetnticacionUsuario(string nombreUsuario, string claveUsuario) {
            Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequest inValue = new Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequest();
            inValue.Body = new Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequestBody();
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.claveUsuario = claveUsuario;
            Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioResponse retVal = ((Caja.ReferenciaServicioUsuario.ServicioAutSoap)(this)).AutetnticacionUsuario(inValue);
            return retVal.Body.AutetnticacionUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioResponse> Caja.ReferenciaServicioUsuario.ServicioAutSoap.AutetnticacionUsuarioAsync(Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequest request) {
            return base.Channel.AutetnticacionUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioResponse> AutetnticacionUsuarioAsync(string nombreUsuario, string claveUsuario) {
            Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequest inValue = new Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequest();
            inValue.Body = new Caja.ReferenciaServicioUsuario.AutetnticacionUsuarioRequestBody();
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.claveUsuario = claveUsuario;
            return ((Caja.ReferenciaServicioUsuario.ServicioAutSoap)(this)).AutetnticacionUsuarioAsync(inValue);
        }
    }
}
