//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAutenticacion.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public decimal id_empleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public decimal departamento_id_departamento { get; set; }
    }
}
